
[project]
name = "sigil-generator"
version = "0.1.0"
description = "3D Mystical Sigil Generator"
dependencies = [
    "flask>=2.0.0",
    "pillow>=9.0.0",
    "numpy>=1.20.0"
]

[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"
